#pragma config(Motor,  port2,           fl,            tmotorVex393, openLoop)
#pragma config(Motor,  port3,           fr,            tmotorVex393, openLoop)
#pragma config(Motor,  port4,           bl,            tmotorVex393, openLoop)
#pragma config(Motor,  port5,           br,            tmotorVex393, openLoop)
#pragma config(Motor,  port6,           claw,          tmotorVex393, openLoop)
#pragma config(Motor,  port7,           arm,           tmotorVex393, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	motor[port2]= 127;
	Motor[port3]= -127;
	Motor[port4]= 127;
	Motor[port5]= -127;
	wait1Msec(4009);//2nd squre red to 1st red cone 4ft 7in

	motor[arm]= 127;
	wait1Msec(2000);

	motor[port2]= 127;
	Motor[port3]= -127;
	Motor[port4]= 127;
	Motor[port5]= -127;
	wait1Msec(750);

	motor[arm]= -127;
	wait1Msec(2000);


	while ( 1 == 1)
	{
		motor[port2]= vexRt[ch3] + vexRt[ch4] + vexRt[ch1];
		Motor[port3]= -VexRT[ch3] + VexRT[ch4] + vexRT[Ch1];
		Motor[port4]= VexRT[ch3] - VexRT[ch4] + vexRT[ch1];
		Motor[port5]= -VexRT[ch3] - VexRT[ch4] + vexRt[ch1];

		if (vexRt[Btn5U] == 1)
		{
			motor[port6] = 127;
		}
		else if (vexRT[BTn5D] == 1)
		{
			motor[port6] = -127;
		}
		else
		{
			motor[port6] = 0;
		}

		if (vexRt[Btn6U] == 1)
		{
			motor[port7] = 127;
		}
		else if (vexRT[BTn6D] == 1)
		{
			motor[port7] = -127;
		}
		else
		{
			motor[port7] = 0;
		}
	}
}
